### ISSUE TITLE
Getting error

### ISSUE THREAD

**Issue by Red1860** [dhinakg/aeota#1]
I am getting this error when using this tool,
Error parsing key
Error loading credentials

Am i doing something wrong?

![Screenshot 2024-06-11 at 10 49 29 AM](https://github.com/dhinakg/aeota/assets/58611972/10cc298e-9db4-4178-98cf-1de1d8f95d9c)

**Comment by dhinakg** [comment]
<img width="425" alt="image" src="https://github.com/dhinakg/aeota/assets/17605561/316461fd-83be-4b52-b0c8-1b20e9858630">

When passing keys to `aea`, they need to be prefixed with `base64:`

**Comment by Red1860** [comment]
Thanks it works!
