### ISSUE TITLE
invalid syntax

### ISSUE THREAD

**Issue by Unagaml** [dhinakg/aeota#2]
python get_key.py /Users/wesker/Downloads/iPhone16,1_18.0_22A5282m_Restore/090-29322-049.dmg.aea
  File "get_key.py", line 30
    print(f"Expected 12 bytes, got {len(header)}")
                                                ^

getting this error
please fix that
<img width="808" alt="Screenshot 2024-06-12 at 15 08 43" src="https://github.com/dhinakg/aeota/assets/92244180/5481c46f-5e7f-4d2c-8c36-e3666d03a68d">

**Comment by e11iot-1337** [comment]
**

> **use "python3" instead of "python"**

**

```
???@MacBook-Pro-??? aeota % python3 get_key.py 

/Users/???/Library/Python/3.8/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Usage: get_key.py <aea>

???@MacBook-Pro-??? aeota % python get_key.py 
  File "get_key.py", line 30
    print(f"Expected 12 bytes, got {len(header)}")
                                                ^
SyntaxError: invalid syntax

???@MacBook-Pro-??? aeota % python3 get_key.py

/Users/???/Library/Python/3.8/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Usage: get_key.py <aea>
```

**Comment by Unagaml** [comment]
Not decrypted 
<img width="1570" alt="Screenshot 2024-06-12 at 17 36 06" src="https://github.com/dhinakg/aeota/assets/92244180/24697b7c-0e2d-43aa-bd87-6543abcb0844">

**Comment by Unagaml** [comment]
> **
> 
> > **use "python3" instead of "python"**
> 
> **
> 
> ```
> ???@MacBook-Pro-??? aeota % python3 get_key.py 
> 
> /Users/???/Library/Python/3.8/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
>   warnings.warn(
> Usage: get_key.py <aea>
> 
> ???@MacBook-Pro-??? aeota % python get_key.py 
>   File "get_key.py", line 30
>     print(f"Expected 12 bytes, got {len(header)}")
>                                                 ^
> SyntaxError: invalid syntax
> 
> ???@MacBook-Pro-??? aeota % python3 get_key.py
> 
> /Users/???/Library/Python/3.8/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
>   warnings.warn(
> Usage: get_key.py <aea>
> ```

please help
