### ISSUE TITLE
Error creating I/O streams

### ISSUE THREAD

**Issue by Unagaml** [dhinakg/aeota#4]
I enter the command to decrypt but it gives an error. Tell me what am I doing wrong???
<img width="1570" alt="Screenshot 2024-06-12 at 22 24 42" src="https://github.com/dhinakg/aeota/assets/92244180/785422c7-cab3-47b6-bb29-f865fcfb017e">

**Comment by dhinakg** [comment]
Is `extract` an existing folder? You are trying to decrypt a dmg wrapped in an aea, so the resulting file would be a dmg, not a folder.

**Comment by Unagaml** [comment]
Yes extract existing folder. So I need to change the extension from aoe to dmg??? Or how? Can you write the exact command on how to do it?

**Comment by Unagaml** [comment]
> Is `extract` an existing folder? You are trying to decrypt a dmg wrapped in an aea, so the resulting file would be a dmg, not a folder.

Yes extract existing folder. So I need to change the extension from aoe to dmg??? Or how? Can you write the exact command on how to do it?

**Comment by dhinakg** [comment]
Make the output parameter point to a file path that doesn't exist, ie. `~/Downloads/090-28430-036.dmg`.
